# Generated by Django 4.1.3 on 2022-11-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CuentasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=15)),
                ('codigo_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_transaccion', models.DecimalField(decimal_places=5, max_digits=15)),
                ('cuenta_bancaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.cuentasbancarias')),
                ('tipo_transaccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.tipotransaccion')),
            ],
        ),
    ]
