# Generated by Django 4.1.3 on 2022-11-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
        migrations.AddField(
            model_name='cuentasbancarias',
            name='numero_cuenta',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cuentasbancarias',
            name='saldo',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='origen',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
