# Generated by Django 4.1.3 on 2022-11-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_cliente_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='rut',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
