# Generated by Django 4.1.3 on 2022-11-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transacciones_fecha_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacciones',
            old_name='fecha_registro',
            new_name='fecha_transaccion',
        ),
    ]
