# Generated by Django 4.1.3 on 2022-11-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_fecha_registro_transacciones_fecha_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='fecha_transaccion',
        ),
    ]
