# Generated by Django 4.1.3 on 2022-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_transacciones_fecha_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='fecha_transaccion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
